name: Build PLJIT

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  pljit:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: threeal/cmake-action@v2.1.0
        with:
          cmake-version: '3.13'

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
          cc: 1

      - name: Create and Build PLJIT with Clang
        run: |
          mkdir ci_build_pljit
          cd ci_build_pljit
          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            ..
          make
          ./test/tester
